//
//  SENUtilities.m
//  HPV
//
//  Created by Jason McDermott on 24/01/2014.
//  Copyright (c) 2014 Sensorium Health. All rights reserved.
//

#import "SENUtilities.h"

@implementation SENUtilities

@synthesize school = _school;

+ (NSString *)getUUID
{
    CFUUIDRef theUUID = CFUUIDCreate(NULL);
    CFStringRef string = CFUUIDCreateString(NULL, theUUID);
    CFRelease(theUUID);
    return (__bridge NSString *)string;
}

+ (NSString*)getUUIDString:(CFUUIDRef)ref
{
    NSString *str = [NSString stringWithFormat:@"%@",ref];
    return [[NSString stringWithFormat:@"%@",str] substringWithRange:NSMakeRange(str.length - 36, 36)];
}

+ (NSString*)getStringForKey:(NSString*)key
{
    NSString* val = @"";
    NSUserDefaults *standardUserDefaults = [NSUserDefaults standardUserDefaults];
    if (standardUserDefaults) val = [standardUserDefaults stringForKey:key];
    if (val == NULL) val = @"";
    return val;
}

+ (void)setStringForKey:(NSString*)value withKey:(NSString*)key
{
	NSUserDefaults *standardUserDefaults = [NSUserDefaults standardUserDefaults];
	if (standardUserDefaults)
    {
		[standardUserDefaults setObject:value forKey:key];
		[standardUserDefaults synchronize];
	}
}


+ (void)setIntForKey:(NSInteger)value withKey:(NSString*)key
{
	NSUserDefaults *standardUserDefaults = [NSUserDefaults standardUserDefaults];
	if (standardUserDefaults)
    {
		[standardUserDefaults setInteger:value forKey:key];
		[standardUserDefaults synchronize];
	}
}

#pragma mark -
#pragma mark Random Number Generators

+ (float)randomFloatInRange:(float)Min :(float)Max;
{
    float rand = Min+(Max-Min)*((float)arc4random())/ULONG_MAX;
//    NSLog(@"float %f",rand);
    return rand;
}

+ (CGFloat)randomCGFloatInRange:(float)Min :(float)Max;
{
    CGFloat rand = Min+(Max-Min)*((CGFloat)arc4random())/ULONG_MAX;
    return rand;
//    NSLog(@"CGFloat %f",rand);
}

+ (int)randomIntInRange:(int)Min :(int)Max;
{
    //    int rand = Min+(Max-Min)*((int)arc4random())/ULONG_MAX;
    int rand = (arc4random() % Max) + 1;
//    NSLog(@"int %d",rand);
    return rand;
}

+ (BOOL)randomBool
{
    int rand = (arc4random() % 2) - 1;
    BOOL result;
    if (rand == 0) {
        result = NO;
    } else {
        result = YES;
    }
//    NSLog(@"bool %hhd",result);
    return result;
}

#pragma mark -
#pragma mark Methods Not Currently In Use



-(NSString*)readXMLFile:(NSString *)file
{
    // function not in use
    NSString *docFile = file;
    NSFileManager *filemgr;
    NSData *databuffer;
    filemgr = [NSFileManager defaultManager];
    databuffer = [filemgr contentsAtPath: docFile];
    return [[NSString alloc] initWithData:databuffer encoding:NSUTF16StringEncoding];
    NSString *a = @"";
    return a;
}

- (void)convertDictionaryToJSON:(NSDictionary *)dict
{
    NSError *error = nil;
    NSData *jsonData = [NSJSONSerialization
                        dataWithJSONObject:dict
                        options:NSJSONWritingPrettyPrinted
                        error:&error];
    
    if ([jsonData length] > 0 && error == nil){
        
        NSLog(@"Successfully serialized the dictionary into data.");
        NSString *jsonString =
        [[NSString alloc] initWithData:jsonData
                              encoding:NSUTF8StringEncoding];
        NSLog(@"JSON String = %@", jsonString);
    }
    else if ([jsonData length] == 0 && error == nil){
        NSLog(@"No data was returned after serialization.");
    }
    else if (error != nil){
        NSLog(@"An error happened = %@", error);
    }
}

+ (unsigned long long)microTime
{
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return ((long long) tv.tv_sec * (long long) 1000000 +
            (long long) tv.tv_usec);
}

+ (double)doubleTime
{
    return [self microTime] / 1000000.0;
}

+ (void)addMessageText:(NSMutableString *)mutableString :(NSString *)text :(UITextView *)textView
{
    
    NSLog(@"%@",text);

//    NSString *responseString = [NSString stringWithFormat:@"%@\r\n%@", text, mutableString];
    [mutableString appendString:[NSString stringWithFormat:@"%@\r\n",text]];
    
    textView.text = mutableString;
    
//    int numLines = textView.contentSize.height/textView.font.lineHeight;
//    [textView scrollRangeToVisible:NSMakeRange(textView.text.length, 0)];
//    if (numLines - previousNumLines > 2){
//        [textView setContentOffset:CGPointMake(0, numLines * textView.font.lineHeight) animated:NO];
//    }
}

+ (NSString *)getNickname:(CBPeripheral *)peripheral
{
    if (peripheral.identifier) {
        CFUUIDBytes uuid  = CFUUIDGetUUIDBytes((__bridge CFUUIDRef)(peripheral.identifier));
        NSString *nick = [NSString stringWithFormat:@"%@ (%@)",[SENUtilities computeNickname:&uuid :sizeof(uuid)],peripheral.name];
        nick = [nick capitalizedString];
        return nick;
    } else {
        if (sizeof(peripheral) == 4) {
            return [NSString stringWithFormat:@"%@ %08lX", peripheral.name, (unsigned long) peripheral];
        } else {
            return [NSString stringWithFormat:@"%@ %016llX", peripheral.name, (unsigned long long) peripheral];
        }
    }
}



static unsigned long long computeHash(const void *data, size_t len) {
    unsigned char digest[CC_MD5_DIGEST_LENGTH];
    CC_MD5(data, len, digest);
    unsigned long long hash = 0;
    for (unsigned i = 0; i < sizeof(digest); i++) {
        hash ^= (digest[i] << (i % 8));
    }
    return hash;
}

+ (NSString *)computeNickname:(const void *)data :(size_t)len
{
    unsigned long long hash = computeHash(data, len);
    const char *placename = placenames[hash % placenameCount];
    int n = (hash / placenameCount) % 10000;
    return [NSString stringWithFormat:@"%s-%d",placename,n];
}

const char *placenames[] = {
    "BARTON",
    "DARWIN",
    "PARAP",
    "ALAWA",
    "BRINKIN",
    "CASUARINA",
    "COCONUT GROVE",
    "JINGILI",
    "LEE POINT",
    "LYONS",
    "MILLNER",
    "MOIL",
    "MUIRHEAD",
    "NAKARA",
    "NIGHTCLIFF",
    "RAPID CREEK",
    "TIWI",
    "WAGAMAN",
    "WANGURI",
    "CASUARINA",
    "ANULA",
    "BUFFALO CREEK",
    "HOLMES",
    "KARAMA",
    "LEANYER",
    "MALAK",
    "MARRARA",
    "NORTHLAKES",
    "SANDERSON",
    "WOODLEIGH GARDENS",
    "WULAGI",
    "SANDERSON",
    "NIGHTCLIFF",
    "BAGOT",
    "BAYVIEW",
    "CHARLES DARWIN",
    "COONAWARRA",
    "CULLEN BAY",
    "DARWIN MC",
    "EAST POINT",
    "EATON",
    "FANNIE BAY",
    "LARRAKEYAH",
    "LUDMILLA",
    "PARAP",
    "RAAF BASE DARWIN",
    "STUART PARK",
    "THE GARDENS",
    "THE NARROWS",
    "WINNELLIE",
    "WOOLNER",
    "WINNELLIE",
    "ACACIA HILLS",
    "ANGURUGU",
    "ANINDILYAKWA",
    "ANNIE RIVER",
    "BATHURST ISLAND",
    "BEES CREEK",
    "BELYUEN",
    "BLACK JUNGLE",
    "BLACKMORE",
    "BORDER STORE",
    "BURRUNDIE",
    "BYNOE",
    "BYNOE HARBOUR",
    "CAMP CREEK",
    "CHANNEL ISLAND",
    "CHARLES DARWIN",
    "CHARLOTTE",
    "CLARAVALE",
    "COBOURG",
    "COLLETT CREEK",
    "COOMALIE CREEK",
    "COX PENINSULA",
    "CROKER ISLAND",
    "DALY",
    "DALY RIVER",
    "DARWIN MC",
    "DARWIN RIVER DAM",
    "DELISSAVILLE",
    "DOUGLAS-DALY",
    "EAST ARM",
    "EAST ARNHEM",
    "ELRUNDIE",
    "EVA VALLEY",
    "FINNISS VALLEY",
    "FLEMING",
    "FLY CREEK",
    "FREDS PASS",
    "GALIWINKU",
    "GLYDE POINT",
    "GOULBURN ISLAND",
    "GUNBALANYA",
    "GUNN POINT",
    "HAYES CREEK",
    "HIDDEN VALLEY",
    "HOTHAM",
    "HUGHES",
    "KAKADU",
    "KOOLPINYAH",
    "LAKE BENNETT",
    "LAMBELLS LAGOON",
    "LITCHFIELD PARK",
    "LIVINGSTONE",
    "LLOYD CREEK",
    "MANDORAH",
    "MANINGRIDA",
    "MARANUNGA",
    "MARGARET RIVER",
    "MARRAKAI",
    "MCMINNS LAGOON",
    "MICKETT CREEK",
    "MIDDLE POINT",
    "MILIKAPITI",
    "MILINGIMBI",
    "MILLWOOD",
    "MILYAKBURRA",
    "MINJILANG",
    "MOUNT BUNDEY",
    "MURRUMUJUK",
    "NAUIYU",
    "NEMARLUK",
    "NGANMARRIYANGA",
    "NGUIU",
    "NUMBULWAR",
    "NUMBURINDI",
    "OENPELLI",
    "PALUMPA",
    "PEPPIMENARTI",
    "PIRLANGIMPI",
    "POINT STEPHENS",
    "POINT STUART",
    "PULARUMPI",
    "RAKULA",
    "RAMINGINING",
    "ROBIN FALLS",
    "RUM JUNGLE",
    "SANDPALMS ROADHOUSE",
    "SOUTHPORT",
    "STAPLETON",
    "THAMARRURR",
    "TIPPERARY",
    "TIVENDALE",
    "TIWI ISLANDS",
    "TORTILLA FLATS",
    "TUMBLING WATERS",
    "UMBAKUMBA",
    "VERNON ISLANDS",
    "WADEYE",
    "WAGAIT BEACH",
    "WAK WAK",
    "WARRUWI",
    "WEDDELL",
    "WEST ARNHEM",
    "WICKHAM",
    "WINNELLIE",
    "WISHART",
    "WOOLANING",
    "BERRIMAH",
    "KNUCKEY LAGOON",
    "HOLTZE",
    "PINELANDS",
    "ARCHER",
    "DRIVER",
    "DURACK",
    "FARRAR",
    "GRAY",
    "MARLOW LAGOON",
    "MOULDEN",
    "PALMERSTON",
    "SHOAL BAY",
    "WOODROFFE",
    "YARRAWONGA",
    "PALMERSTON",
    "BAKEWELL",
    "BELLAMACK",
    "GUNN",
    "JOHNSTON",
    "MITCHELL",
    "ROSEBERY",
    "ROSEBERY HEIGHTS",
    "ZUCCOLI",
    "COOLALINGA",
    "HOWARD SPRINGS",
    "VIRGINIA",
    "GIRRAWEEN",
    "HERBERT",
    "HUMPTY DOO",
    "MANTON",
    "NOONAMAH",
    "BERRY SPRINGS",
    "DUNDEE FOREST",
    "DARWIN RIVER",
    "BATCHELOR",
    "ADELAIDE RIVER",
    "PINE CREEK",
    "COSSACK",
    "EMUNGALAN",
    "KATHERINE",
    "LANSDOWNE",
    "KATHERINE",
    "ARNOLD",
    "BAINES",
    "BARUNGA",
    "BESWICK",
    "BESWICK CREEK",
    "BINJARI",
    "BIRDUM",
    "BRADSHAW",
    "BUCHANAN",
    "BULMAN WEEMOL",
    "CRESWELL",
    "DAGURAGU",
    "DALY WATERS",
    "DELAMERE",
    "DUNMARRA",
    "EDITH",
    "ELSEY",
    "ELSEY STATION",
    "FLORINA",
    "FLYING FOX",
    "GREGORY",
    "GULUNG MARDRULK",
    "GURINDJI",
    "JILKMINGGAN",
    "KALKARINDJI",
    "KATHERINE",
    "LAJAMANU",
    "LARRIMAH",
    "LIMMEN",
    "MANBULLOO",
    "MARANBOY",
    "MATARANKA",
    "MCARTHUR",
    "MINIYERI",
    "NGUKURR",
    "NITMILUK",
    "PELLEW ISLANDS",
    "PIGEON HOLE",
    "ROBINSON RIVER",
    "STURT PLATEAU",
    "TANAMI EAST",
    "TIMBER CREEK",
    "TOP SPRINGS",
    "URALLA",
    "VENN",
    "VICTORIA RIVER",
    "VICTORIA RIVER DOWNS",
    "WARUMUNGU",
    "WAVE HILL",
    "WILTON",
    "YARRALIN",
    "TINDAL",
    "BORROLOOLA",
    "KING ASH BAY",
    "TENNANT CREEK",
    "BRUNCHILLY",
    "TENNANT CREEK",
    "AVON DOWNS",
    "CALVERT",
    "CRESSWELL DOWNS",
    "ELLIOTT",
    "HELEN SPRINGS",
    "MUCKATY STATION",
    "NEWCASTLE WATERS",
    "NICHOLSON",
    "PAMAYU",
    "PHILLIP CREEK STATION",
    "RENNER SPRINGS",
    "TABLELANDS",
    "TENNANT CREEK",
    "THREE WAYS",
    "WARREGO",
    "WOLLOGORANG STATION",
    "WYCLIFFE WELL",
    "ALICE SPRINGS",
    "ARALUEN",
    "ARUMBERA",
    "BRAITLING",
    "CICCONE",
    "CONNELLAN",
    "DESERT SPRINGS",
    "EAST SIDE",
    "FLYNN",
    "GILLEN",
    "ILPARPA",
    "IRLPME",
    "LARAPINTA",
    "MOUNT JOHNS",
    "ROSS",
    "SADADEEN",
    "STUART",
    "THE GAP",
    "UNDOOLYA",
    "WHITE GUMS",
    "ALICE SPRINGS",
    "AHERRENGE",
    "ALI CURUNG",
    "ALICE SPRINGS",
    "AMATA",
    "AMOONGUNA",
    "AMPILATWATJA",
    "ANATYE",
    "ANMATJERE",
    "ANTEWENEGERRDE",
    "AREYONGA",
    "ATITJERE",
    "AYERS ROCK",
    "BARROW CREEK",
    "BURT PLAIN",
    "CANTEEN CREEK",
    "CHILLA WELL",
    "COSTELLO",
    "DAVENPORT",
    "DOCKER RIVER",
    "ENGAWALA",
    "ERLDUNDA",
    "ERNABELLA",
    "FINKE",
    "FREGON",
    "GHAN",
    "GIBSON DESERT NORTH",
    "GIBSON DESERT SOUTH",
    "HAASTS BLUFF",
    "HALE",
    "HART",
    "HART RANGE",
    "HERMANNSBURG",
    "HUGH",
    "IMANPA",
    "INDULKANA",
    "ININTI STORE",
    "JAY CREEK",
    "KALTUKATJARA",
    "KINTORE",
    "KIWIRRKURRA",
    "KULGERA",
    "KUNPARRKA",
    "LAKE MACKAY",
    "LARAMBA",
    "MEREENIE",
    "MIMILI",
    "MOUNT LIEBIG",
    "MOUNT ZEIL",
    "MULGA BORE",
    "MURPUTJA HOMELANDS",
    "MUTITJULU",
    "NAMATJIRA",
    "NGAANYATJARRA-GILES",
    "NYAPARI",
    "NYIRRIPI",
    "PAPUNYA",
    "PATJARR",
    "PETERMANN",
    "PITJANTJATJARA HOMELANDS",
    "SANDOVER",
    "SANTA TERESA",
    "SIMPSON",
    "TANAMI",
    "TARA",
    "THANGKENHARENGE",
    "TI TREE",
    "TITJIKALA",
    "TJIRRKARLI",
    "TJUKURLA",
    "ULURU",
    "UMPANGARA",
    "URAPUNTJA",
    "WALLACE ROCKHOLE",
    "WANARN",
    "WILLOWRA",
    "WILORA",
    "WINGELLINA",
    "WUTUNUGURRA",
    "YUELAMU",
    "YUENDUMU",
    "YULARA",
    "GAPUWIYAK",
    "GOVE",
    "GUNYANGARA",
    "NHULUNBUY",
    "YIRRKALA",
    "NHULUNBUY",
    "ALYANGULA",
    "JABIRU",
    "WINNELLIE",
    "SYDNEY",
    "HAYMARKET",
    "AUSTRALIA SQUARE",
    "GROSVENOR PLACE",
    "ROYAL EXCHANGE",
    "QUEEN VICTORIA BUILDING",
    "SYDNEY SOUTH",
    "DARLINGHURST",
    "EASTERN SUBURBS MC",
    "POTTS POINT",
    "KINGS CROSS",
    "WOOLLAHRA",
    "BONDI JUNCTION",
    "DOUBLE BAY",
    "ATO ACTIVITY STATEMENTS",
    "BROADWAY",
    "SOUTHERN SUBURBS MC",
    "STRAWBERRY HILLS",
    "EVELEIGH",
    "ALEXANDRIA",
    "WATERLOO",
    "WATERLOO",
    "ROSEBERY",
    "CAMPERDOWN",
    "BOTANY",
    "MASCOT",
    "KENSINGTON",
    "UNSW SYDNEY",
    "DRUMMOYNE",
    "MARRICKVILLE",
    "MARRICKVILLE",
    "KINGSGROVE",
    "HURSTVILLE BC",
    "KINGSGROVE DC",
    "KOGARAH",
    "KOGARAH",
    "MIRANDA",
    "HURSTVILLE",
    "CARINGBAH",
    "SUTHERLAND",
    "WEST CHATSWOOD",
    "NORTHBRIDGE",
    "MILSONS POINT",
    "ARTARMON",
    "CROWS NEST",
    "CROWS NEST",
    "ST LEONARDS",
    "HORNSBY",
    "HORNSBY WESTFIELD",
    "FRENCHS FOREST",
    "MANLY",
    "MONA VALE",
    "MONA VALE",
    "NORTH RYDE BC",
    "GLADESVILLE",
    "RYDE",
    "WEST RYDE",
    "NORTHERN SUBURBS MC",
    "ERMINGTON",
    "RYDALMERE BC",
    "EPPING",
    "EPPING",
    "PENNANT HILLS",
    "SEVEN HILLS",
    "PARRAMATTA",
    "PARRAMATTA",
    "NORTH PARRAMATTA",
    "BAULKHAM HILLS",
    "CASTLE HILL",
    "PENNANT HILLS",
    "SEVEN HILLS MC",
    "ST MARYS",
    "PENRITH SOUTH DC",
    "ASHFIELD",
    "BURWOOD",
    "SILVERWATER",
    "STRATHFIELD",
    "LIDCOMBE",
    "GRANVILLE",
    "AUBURN",
    "GUILDFORD",
    "WETHERILL PARK DC",
    "FAIRFIELD",
    "LIVERPOOL",
    "MOOREBANK",
    "BANKSTOWN",
    "INGLEBURN",
    "MILPERRA",
    "LEIGHTONFIELD MC",
    "LEIGHTONFIELD MC",
    "BARANGAROO",
    "DAWES POINT",
    "HAYMARKET",
    "MILLERS POINT",
    "PARLIAMENT HOUSE",
    "SYDNEY",
    "SYDNEY SOUTH",
    "THE ROCKS",
    "SYDNEY",
    "WORLD SQUARE",
    "ALEXANDRIA MC",
    "EASTERN SUBURBS MC",
    "BROADWAY",
    "ULTIMO",
    "CHIPPENDALE",
    "DARLINGTON",
    "PYRMONT",
    "DARLINGHURST",
    "SURRY HILLS",
    "ELIZABETH BAY",
    "HMAS KUTTABUL",
    "POTTS POINT",
    "RUSHCUTTERS BAY",
    "WOOLLOOMOOLOO",
    "STRAWBERRY HILLS",
    "ALEXANDRIA",
    "BEACONSFIELD",
    "EVELEIGH",
    "REDFERN",
    "WATERLOO",
    "ZETLAND",
    "EASTLAKES",
    "ROSEBERY",
    "BANKSMEADOW",
    "BOTANY",
    "MASCOT",
    "CENTENNIAL PARK",
    "MOORE PARK",
    "PADDINGTON",
    "BONDI JUNCTION",
    "QUEENS PARK",
    "BELLEVUE HILL",
    "BRONTE",
    "WAVERLEY",
    "WOOLLAHRA",
    "BONDI",
    "BONDI BEACH",
    "NORTH BONDI",
    "TAMARAMA",
    "DARLING POINT",
    "EDGECLIFF",
    "HMAS RUSHCUTTERS",
    "POINT PIPER",
    "DOUBLE BAY",
    "ROSE BAY",
    "DOVER HEIGHTS",
    "HMAS WATSON",
    "ROSE BAY NORTH",
    "VAUCLUSE",
    "WATSONS BAY",
    "CLOVELLY",
    "CLOVELLY WEST",
    "RANDWICK",
    "ST PAULS",
    "DACEYVILLE",
    "KINGSFORD",
    "KENSINGTON",
    "COOGEE",
    "SOUTH COOGEE",
    "MAROUBRA",
    "MAROUBRA SOUTH",
    "PAGEWOOD",
    "CHIFLEY",
    "EASTGARDENS",
    "HILLSDALE",
    "LA PEROUSE",
    "LITTLE BAY",
    "MALABAR",
    "MATRAVILLE",
    "PHILLIP BAY",
    "PORT BOTANY",
    "FOREST LODGE",
    "GLEBE",
    "ANNANDALE",
    "ROZELLE",
    "LEICHHARDT",
    "LILYFIELD",
    "BALMAIN",
    "BALMAIN EAST",
    "BIRCHGROVE",
    "ENMORE",
    "NEWTOWN",
    "ERSKINEVILLE",
    "ST PETERS",
    "SYDENHAM",
    "TEMPE",
    "HABERFIELD",
    "ABBOTSFORD",
    "CANADA BAY",
    "CHISWICK",
    "FIVE DOCK",
    "RODD POINT",
    "RUSSELL LEA",
    "WAREEMBA",
    "DRUMMOYNE",
    "STANMORE",
    "WESTGATE",
    "LEWISHAM",
    "PETERSHAM",
    "PETERSHAM NORTH",
    "CAMPERDOWN",
    "MISSENDEN ROAD",
    "UNSW SYDNEY",
    "NORTH SYDNEY",
    "CHATSWOOD",
    "NORTHERN SUBURBS MC",
    "NORTH SYDNEY",
    "HMAS PLATYPUS",
    "HMAS WATERHEN",
    "LAVENDER BAY",
    "MCMAHONS POINT",
    "NORTH SYDNEY",
    "NORTH SYDNEY SHOPPINGWORLD",
    "WAVERTON",
    "KIRRIBILLI",
    "MILSONS POINT",
    "CAMMERAY",
    "NORTHBRIDGE",
    "ARTARMON",
    "CROWS NEST",
    "GREENWICH",
    "NAREMBURN",
    "ST LEONARDS",
    "WOLLSTONECRAFT",
    "LANE COVE",
    "LANE COVE NORTH",
    "LANE COVE WEST",
    "LINLEY POINT",
    "LONGUEVILLE",
    "NORTHWOOD",
    "RIVERVIEW",
    "CHATSWOOD",
    "CHATSWOOD WEST",
    "CASTLECRAG",
    "MIDDLE COVE",
    "NORTH WILLOUGHBY",
    "WILLOUGHBY",
    "WILLOUGHBY EAST",
    "WILLOUGHBY NORTH",
    "CASTLE COVE",
    "ROSEVILLE",
    "ROSEVILLE CHASE",
    "EAST LINDFIELD",
    "LINDFIELD",
    "LINDFIELD WEST",
    "EAST KILLARA",
    "KILLARA",
    "GORDON",
    "PYMBLE",
    "WEST PYMBLE",
    "NORTH TURRAMURRA",
    "SOUTH TURRAMURRA",
    "TURRAMURRA",
    "WARRAWEE",
    "ST IVES",
    "ST IVES CHASE",
    "NORMANHURST",
    "NORTH WAHROONGA",
    "WAHROONGA",
    "ASQUITH",
    "HORNSBY",
    "HORNSBY HEIGHTS",
    "WAITARA",
    "MOUNT COLAH",
    "MOUNT KURING-GAI",
    "BEROWRA",
    "COWAN",
    "BEROWRA CREEK",
    "BEROWRA HEIGHTS",
    "BEROWRA WATERS",
    "BAR POINT",
    "BROOKLYN",
    "CHEERO POINT",
    "COGRA BAY",
    "DANGAR ISLAND",
    "MILSONS PASSAGE",
    "MOONEY MOONEY",
    "COTTAGE POINT",
    "DUFFYS FOREST",
    "TERREY HILLS",
    "BELROSE",
    "BELROSE WEST",
    "DAVIDSON",
    "FRENCHS FOREST",
    "FRENCHS FOREST EAST",
    "FORESTVILLE",
    "KILLARNEY HEIGHTS",
    "MOSMAN",
    "SPIT JUNCTION",
    "NEUTRAL BAY",
    "NEUTRAL BAY JUNCTION",
    "CREMORNE",
    "CREMORNE JUNCTION",
    "CREMORNE POINT",
    "HMAS PENGUIN",
    "SEAFORTH",
    "BALGOWLAH",
    "BALGOWLAH HEIGHTS",
    "CLONTARF",
    "MANLY VALE",
    "NORTH BALGOWLAH",
    "FAIRLIGHT",
    "MANLY",
    "MANLY EAST",
    "CURL CURL",
    "FRESHWATER",
    "QUEENSCLIFF",
    "COLLAROY",
    "COLLAROY BEACH",
    "COLLAROY PLATEAU WEST",
    "WHEELER HEIGHTS",
    "CROMER",
    "DEE WHY",
    "NARRAWEENA",
    "NORTH CURL CURL",
    "ALLAMBIE HEIGHTS",
    "BEACON HILL",
    "BROOKVALE",
    "NORTH MANLY",
    "OXFORD FALLS",
    "WARRINGAH MALL",
    "ELANORA HEIGHTS",
    "INGLESIDE",
    "NARRABEEN",
    "NORTH NARRABEEN",
    "WARRIEWOOD",
    "WARRIEWOOD SHOPPING SQUARE",
    "MONA VALE",
    "BAYVIEW",
    "CHURCH POINT",
    "ELVINA BAY",
    "LOVETT BAY",
    "MORNING BAY",
    "SCOTLAND ISLAND",
    "NEWPORT",
    "NEWPORT BEACH",
    "AVALON",
    "AVALON BEACH",
    "BILGOLA",
    "CLAREVILLE",
    "WHALE BEACH",
    "COASTERS RETREAT",
    "GREAT MACKEREL BEACH",
    "PALM BEACH",
    "HUNTERS HILL",
    "WOOLWICH",
    "BORONIA PARK",
    "GLADESVILLE",
    "HENLEY",
    "HUNTLEYS COVE",
    "HUNTLEYS POINT",
    "MONASH PARK",
    "TENNYSON POINT",
    "DENISTONE EAST",
    "PUTNEY",
    "RYDE",
    "BLENHEIM ROAD",
    "EAST RYDE",
    "MACQUARIE CENTRE",
    "MACQUARIE PARK",
    "NORTH RYDE",
    "DENISTONE",
    "DENISTONE WEST",
    "MEADOWBANK",
    "MELROSE PARK",
    "WEST RYDE",
    "ERMINGTON",
    "RYDALMERE",
    "DUNDAS",
    "DUNDAS VALLEY",
    "OATLANDS",
    "TELOPEA",
    "CARLINGFORD",
    "CARLINGFORD COURT",
    "CARLINGFORD NORTH",
    "KINGSDENE",
    "BEECROFT",
    "CHELTENHAM",
    "PENNANT HILLS",
    "THORNLEIGH",
    "WESTLEIGH",
    "EPPING",
    "NORTH EPPING",
    "EASTWOOD",
    "MARSFIELD",
    "PARRAMATTA",
    "PARRAMATTA",
    "WEST PENNANT HILLS",
    "CHERRYBROOK",
    "NEWINGTON",
    "SYDNEY OLYMPIC PARK",
    "WENTWORTH POINT",
    "SILVERWATER",
    "SYDNEY MARKETS",
    "SUMMER HILL",
    "ASHFIELD",
    "CROYDON",
    "CROYDON PARK",
    "ENFIELD SOUTH",
    "BURWOOD",
    "BURWOOD NORTH",
    "STRATHFIELD",
    "BURWOOD HEIGHTS",
    "ENFIELD",
    "STRATHFIELD SOUTH",
    "BREAKFAST POINT",
    "CABARITA",
    "CONCORD",
    "MORTLAKE",
    "NORTH STRATHFIELD",
    "CONCORD WEST",
    "LIBERTY GROVE",
    "RHODES",
    "HOMEBUSH",
    "HOMEBUSH SOUTH",
    "HOMEBUSH WEST",
    "BERALA",
    "LIDCOMBE",
    "LIDCOMBE NORTH",
    "ROOKWOOD",
    "BLAXCELL",
    "CAMELLIA",
    "CLYDE",
    "GRANVILLE",
    "HOLROYD",
    "ROSEHILL",
    "SOUTH GRANVILLE",
    "BIRRONG",
    "POTTS HILL",
    "REGENTS PARK",
    "AUBURN",
    "CONSTITUTION HILL",
    "GIRRAWEEN",
    "GREYSTANES",
    "MAYS HILL",
    "PEMULWUY",
    "PENDLE HILL",
    "SOUTH WENTWORTHVILLE",
    "WENTWORTHVILLE",
    "WESTMEAD",
    "OLD TOONGABBIE",
    "TOONGABBIE",
    "TOONGABBIE EAST",
    "KINGS LANGLEY",
    "LALOR PARK",
    "SEVEN HILLS",
    "SEVEN HILLS WEST",
    "ARNDELL PARK",
    "BLACKTOWN",
    "BLACKTOWN WESTPOINT",
    "HUNTINGWOOD",
    "KINGS PARK",
    "MARAYONG",
    "PROSPECT",
    "HARRIS PARK",
    "PARRAMATTA",
    "PARRAMATTA WESTFIELD",
    "NORTH PARRAMATTA",
    "NORTH ROCKS",
    "NORTHMEAD",
    "BAULKHAM HILLS",
    "BELLA VISTA",
    "WINSTON HILLS",
    "CASTLE HILL",
    "BEAUMONT HILLS",
    "KELLYVILLE",
    "KELLYVILLE RIDGE",
    "ROUSE HILL",
    "ANNANGROVE",
    "GLENHAVEN",
    "KENTHURST",
    "CANOELANDS",
    "FOREST GLEN",
    "GLENORIE",
    "DURAL",
    "MIDDLE DURAL",
    "ROUND CORNER",
    "ARCADIA",
    "BERRILEE",
    "FIDDLETOWN",
    "GALSTON",
    "MERRYLANDS",
    "MERRYLANDS WEST",
    "GUILDFORD",
    "GUILDFORD WEST",
    "OLD GUILDFORD",
    "YENNORA",
    "CHESTER HILL",
    "SEFTON",
    "CARRAMAR",
    "LANSDOWNE",
    "VILLAWOOD",
    "SMITHFIELD",
    "SMITHFIELD WEST",
    "WETHERILL PARK",
    "WOODPARK",
    "FAIRFIELD",
    "FAIRFIELD EAST",
    "FAIRFIELD HEIGHTS",
    "FAIRFIELD WEST",
    "CABRAMATTA",
    "CABRAMATTA WEST",
    "CANLEY HEIGHTS",
    "CANLEY VALE",
    "LANSVALE",
    "GLENFIELD",
    "ASHCROFT",
    "BUSBY",
    "CARTWRIGHT",
    "GREEN VALLEY",
    "HECKENBERG",
    "HINCHINBROOK",
    "MILLER",
    "SADLEIR",
    "CASULA",
    "CASULA MALL",
    "CHIPPING NORTON",
    "HAMMONDVILLE",
    "LIVERPOOL",
    "LIVERPOOL SOUTH",
    "LIVERPOOL WESTFIELD",
    "LURNEA",
    "MOOREBANK",
    "MOUNT PRITCHARD",
    "PRESTONS",
    "WARWICK FARM",
    "CECIL HILLS",
    "ELIZABETH HILLS",
    "HORNINGSEA PARK",
    "HOXTON PARK",
    "LEN WATERS ESTATE",
    "MIDDLETON GRANGE",
    "WEST HOXTON",
    "PLEASURE POINT",
    "SANDY POINT",
    "VOYAGER POINT",
    "HOLSWORTHY",
    "WATTLE GROVE",
    "EDMONDSON PARK",
    "INGLEBURN MILPO",
    "HORSLEY PARK",
    "ABBOTSBURY",
    "BOSSLEY PARK",
    "EDENSOR PARK",
    "GREENFIELD PARK",
    "PRAIRIEWOOD",
    "ST JOHNS PARK",
    "WAKELEY",
    "BONNYRIGG",
    "BONNYRIGG HEIGHTS",
    "CECIL PARK",
    "KEMPS CREEK",
    "MOUNT VERNON",
    "AUSTRAL",
    "LEPPINGTON",
    "CHULLORA",
    "GREENACRE",
    "MOUNT LEWIS",
    "BELFIELD",
    "BELMORE",
    "ASHBURY",
    "CANTERBURY",
    "HURLSTONE PARK",
    "CAMPSIE",
    "LAKEMBA",
    "WILEY PARK",
    "PUNCHBOWL",
    "ROSELANDS",
    "BASS HILL",
    "GEORGES HALL",
    "YAGOONA",
    "YAGOONA WEST",
    "BANKSTOWN",
    "BANKSTOWN AERODROME",
    "BANKSTOWN NORTH",
    "BANKSTOWN SQUARE",
    "CONDELL PARK",
    "MANAHAN",
    "MOUNT LEWIS",
    "DULWICH HILL",
    "MARRICKVILLE",
    "MARRICKVILLE METRO",
    "MARRICKVILLE SOUTH",
    "ARNCLIFFE",
    "TURRELLA",
    "WOLLI CREEK",
    "CLEMTON PARK",
    "EARLWOOD",
    "BARDWELL PARK",
    "BARDWELL VALLEY",
    "BEXLEY",
    "BEXLEY NORTH",
    "BEXLEY SOUTH",
    "KINGSGROVE",
    "KINGSWAY WEST",
    "BEVERLY HILLS",
    "NARWEE",
    "LUGARNO",
    "PEAKHURST",
    "PEAKHURST HEIGHTS",
    "RIVERWOOD",
    "PADSTOW",
    "PADSTOW HEIGHTS",
    "REVESBY",
    "REVESBY HEIGHTS",
    "REVESBY NORTH",
    "EAST HILLS",
    "PANANIA",
    "PICNIC POINT",
    "MILPERRA",
    "BANKSIA",
    "BRIGHTON-LE-SANDS",
    "KYEEMAGH",
    "ROCKDALE",
    "BEVERLEY PARK",
    "KOGARAH",
    "KOGARAH BAY",
    "MONTEREY",
    "RAMSGATE",
    "RAMSGATE BEACH",
    "ALLAWAH",
    "CARLTON",
    "DOLLS POINT",
    "SANDRINGHAM",
    "SANS SOUCI",
    "HURSTVILLE",
    "HURSTVILLE GROVE",
    "HURSTVILLE WESTFIELD",
    "BLAKEHURST",
    "CARSS PARK",
    "CONNELLS POINT",
    "KYLE BAY",
    "SOUTH HURSTVILLE",
    "PENSHURST",
    "MORTDALE",
    "OATLEY",
    "KANGAROO POINT",
    "SYLVANIA",
    "SYLVANIA SOUTHGATE",
    "SYLVANIA WATERS",
    "OYSTER BAY",
    "BONNET BAY",
    "COMO",
    "JANNALI",
    "GYMEA",
    "GYMEA BAY",
    "MIRANDA",
    "YOWIE BAY",
    "CARINGBAH",
    "CARINGBAH SOUTH",
    "DOLANS BAY",
    "LILLI PILLI",
    "PORT HACKING",
    "TAREN POINT",
    "BUNDEENA",
    "BURRANEER",
    "CRONULLA",
    "MAIANBAR",
    "WOOLOOWARE",
    "KURNELL",
    "AUDLEY",
    "GARIE",
    "GRAYS POINT",
    "KAREELA",
    "KIRRAWEE",
    "LOFTUS",
    "SUTHERLAND",
    "WORONORA",
    "ENGADINE",
    "HEATHCOTE",
    "WATERFALL",
    "WORONORA HEIGHTS",
    "YARRAWARRAH",
    "ALFORDS POINT",
    "BANGOR",
    "BARDEN RIDGE",
    "ILLAWONG",
    "LUCAS HEIGHTS",
    "MENAI",
    "MENAI CENTRAL",
    "BUCKETTY",
    "CALGA",
    "CENTRAL MANGROVE",
    "EAST GOSFORD",
    "ERINA",
    "ERINA FAIR",
    "GLENWORTH VALLEY",
    "GOSFORD",
    "GREENGROVE",
    "HOLGATE",
    "KARIONG",
    "KULNURA",
    "LISAROW",
    "LOWER MANGROVE",
    "MANGROVE CREEK",
    "MANGROVE MOUNTAIN",
    "MATCHAM",
    "MOONEY MOONEY CREEK",
    "MOUNT ELLIOT",
    "MOUNT WHITE",
    "NARARA",
    "NIAGARA PARK",
    "NORTH GOSFORD",
    "PEATS RIDGE",
    "POINT CLARE",
    "POINT FREDERICK",
    "SOMERSBY",
    "SPRINGFIELD",
    "TASCOTT",
    "TEN MILE HOLLOW",
    "UPPER MANGROVE",
    "WENDOREE PARK",
    "WEST GOSFORD",
    "WYOMING",
    "AVOCA BEACH",
    "BENSVILLE",
    "BOUDDI",
    "COPACABANA",
    "DAVISTOWN",
    "GREEN POINT",
    "KINCUMBER",
    "KINCUMBER SOUTH",
    "MACMASTERS BEACH",
    "PICKETTS VALLEY",
    "SARATOGA",
    "YATTALUNGA",
    "CENTRAL COAST MC",
    "BLACKWALL",
    "HORSFIELD BAY",
    "KOOLEWONG",
    "LITTLE WOBBY",
    "PATONGA",
    "PEARL BEACH",
    "PHEGANS BAY",
    "WONDABYNE",
    "WOY WOY",
    "WOY WOY BAY",
    "BOOKER BAY",
    "BOX HEAD",
    "DALEYS POINT",
    "EMPIRE BAY",
    "ETTALONG BEACH",
    "HARDYS BAY",
    "KILLCARE",
    "KILLCARE HEIGHTS",
    "PRETTY BEACH",
    "ST HUBERTS ISLAND",
    "UMINA BEACH",
    "WAGSTAFFE",
    "FOUNTAINDALE",
    "KANGY ANGY",
    "OURIMBAH",
    "PALM GROVE",
    "PALMDALE",
    "ALISON",
    "BUSHELLS RIDGE",
    "CEDAR BRUSH CREEK",
    "CHAIN VALLEY BAY",
    "CRANGAN BAY",
    "DOORALONG",
    "DURREN DURREN",
    "FRAZER PARK",
    "FREEMANS",
    "GWANDALAN",
    "HALLORAN",
    "HAMLYN TERRACE",
    "JILLIBY",
    "KANWAL",
    "KIAR",
    "KINGFISHER SHORES",
    "LAKE MUNMORAH",
    "LEMON TREE",
    "LITTLE JILLIBY",
    "MANNERING PARK",
    "MARDI",
    "MOONEE",
    "POINT WOLSTONCROFT",
    "RAVENSDALE",
    "ROCKY POINT",
    "SUMMERLAND POINT",
    "TACOMA",
    "TACOMA SOUTH",
    "TUGGERAH",
    "TUGGERAWONG",
    "WADALBA",
    "WALLARAH",
    "WARNERVALE",
    "WATANOBBI",
    "WOONGARRAH",
    "WYBUNG",
    "WYEE",
    "WYEE POINT",
    "WYONG",
    "WYONG CREEK",
    "WYONGAH",
    "YARRAMALONG",
    "ERINA HEIGHTS",
    "FORRESTERS BEACH",
    "NORTH AVOCA",
    "TERRIGAL",
    "WAMBERAL",
    "BATEAU BAY",
    "BAY VILLAGE",
    "BERKELEY VALE",
    "BLUE BAY",
    "CHITTAWAY BAY",
    "CHITTAWAY POINT",
    "GLENNING VALLEY",
    "KILLARNEY VALE",
    "LONG JETTY",
    "MAGENTA",
    "SHELLY BEACH",
    "THE ENTRANCE",
    "THE ENTRANCE NORTH",
    "TOOWOON BAY",
    "TUMBI UMBI",
    "BLUE HAVEN",
    "BUDGEWOI",
    "BUDGEWOI PENINSULA",
    "BUFF POINT",
    "COLONGRA",
    "DOYALSON",
    "DOYALSON NORTH",
    "HALEKULANI",
    "SAN REMO",
    "CANTON BEACH",
    "CHARMHAVEN",
    "GOROKAN",
    "LAKE HAVEN",
    "NORAH HEAD",
    "NORAVILLE",
    "TOUKLEY",
    "BALCOLYN",
    "BONNELLS BAY",
    "BRIGHTWATERS",
    "DORA CREEK",
    "ERARING",
    "MANDALONG",
    "MIRRABOOKA",
    "MORISSET",
    "MORISSET PARK",
    "MYUNA BAY",
    "SILVERWATER",
    "SUNSHINE",
    "WINDERMERE PARK",
    "YARRAWONGA PARK",
    "COORANBONG",
    "MARTINSVILLE",
    "WANGI WANGI",
    "BARNSLEY",
    "KILLINGWORTH",
    "WAKEFIELD",
    "BELMONT",
    "BELMONT NORTH",
    "BELMONT SOUTH",
    "CROUDACE BAY",
    "FLORAVILLE",
    "JEWELLS",
    "MARKS POINT",
    "VALENTINE",
    "BLACKSMITHS",
    "CAMS WHARF",
    "CATHERINE HILL BAY",
    "CAVES BEACH",
    "LITTLE PELICAN",
    "MURRAYS BEACH",
    "NORDS WHARF",
    "PELICAN",
    "PINNY BEACH",
    "SWANSEA",
    "SWANSEA HEADS",
    "ELEEBANA",
    "LAKELANDS",
    "WARNERS BAY",
    "ARCADIA VALE",
    "AWABA",
    "BALMORAL",
    "BLACKALLS PARK",
    "BOLTON POINT",
    "BUTTABA",
    "CAREY BAY",
    "COAL POINT",
    "FASSIFERN",
    "FENNELL BAY",
    "FISHING POINT",
    "KILABEN BAY",
    "RATHMINES",
    "RYHOPE",
    "TORONTO",
    "ARGENTON",
    "BOOLAROO",
    "BOORAGUL",
    "MARMONG POINT",
    "SPEERS POINT",
    "TERALBA",
    "WOODRISING",
    "CAMERON PARK",
    "CARDIFF",
    "CARDIFF HEIGHTS",
    "CARDIFF SOUTH",
    "EDGEWORTH",
    "GLENDALE",
    "MACQUARIE HILLS",
    "HOLMESVILLE",
    "SEAHAMPTON",
    "WEST WALLSEND",
    "BIRMINGHAM GARDENS",
    "ELERMORE VALE",
    "FLETCHER",
    "MARYLAND",
    "MINMI",
    "RANKIN PARK",
    "WALLSEND",
    "WALLSEND SOUTH",
    "ADAMSTOWN",
    "ADAMSTOWN HEIGHTS",
    "GARDEN SUBURB",
    "HIGHFIELDS",
    "KOTARA",
    "KOTARA FAIR",
    "KOTARA SOUTH",
    "BENNETTS GREEN",
    "CHARLESTOWN",
    "DUDLEY",
    "GATESHEAD",
    "HILLSBOROUGH",
    "KAHIBAH",
    "MOUNT HUTTON",
    "REDHEAD",
    "TINGIRA HEIGHTS",
    "WHITEBRIDGE",
    "MEREWETHER",
    "MEREWETHER HEIGHTS",
    "THE JUNCTION",
    "BROADMEADOW",
    "HAMILTON NORTH",
    "MARYVILLE",
    "WICKHAM",
    "CARRINGTON",
    "FERN BAY",
    "STOCKTON",
    "ISLINGTON",
    "TIGHES HILL",
    "GEORGETOWN",
    "WARATAH",
    "WARATAH WEST",
    "JESMOND",
    "LAMBTON",
    "NORTH LAMBTON",
    "BAR BEACH",
    "COOKS HILL",
    "NEWCASTLE",
    "NEWCASTLE EAST",
    "THE HILL",
    "NEWCASTLE WEST",
    "HAMILTON",
    "HAMILTON EAST",
    "HAMILTON SOUTH",
    "KOORAGANG",
    "MAYFIELD",
    "MAYFIELD EAST",
    "MAYFIELD NORTH",
    "MAYFIELD WEST",
    "SANDGATE",
    "WARABROOK",
    "KOTARA EAST",
    "NEW LAMBTON",
    "NEW LAMBTON HEIGHTS",
    "WINDALE",
    "SHORTLAND",
    "CALLAGHAN",
    "DANGAR",
    "HUNTER REGION MC",
    "ALLYNBROOK",
    "BINGLEBURRA",
    "CARRABOLLA",
    "EAST GRESFORD",
    "ECCLESTON",
    "GRESFORD",
    "HALTON",
    "LEWINSBROOK",
    "LOSTOCK",
    "MOUNT RIVERS",
    "UPPER ALLYN",
    "MINIMBAH",
    "NABIAC",
    "WILLIAMTOWN RAAF",
    "CORLETTE",
    "FINGAL BAY",
    "NELSON BAY",
    "SHOAL BAY",
    "ANNA BAY",
    "BOAT HARBOUR",
    "BOBS FARM",
    "FISHERMANS BAY",
    "ONE MILE",
    "TAYLORS BEACH",
    "SALAMANDER BAY",
    "SOLDIERS POINT",
    "CAMPVALE",
    "FERODALE",
    "FULLERTON COVE",
    "MEDOWIE",
    "OYSTER COVE",
    "SALT ASH",
    "WILLIAMTOWN",
    "LEMON TREE PASSAGE",
    "MALLABULA",
    "TANILBA BAY",
    "TILLIGERRY CREEK",
    "ABERGLASSLYN",
    "ALLANDALE",
    "ANAMBAH",
    "BOLWARRA",
    "BOLWARRA HEIGHTS",
    "FARLEY",
    "GLEN OAK",
    "GOSFORTH",
    "HILLSBOROUGH",
    "HORSESHOE BEND",
    "KEINBAH",
    "LARGS",
    "LORN",
    "LOUTH PARK",
    "MAITLAND",
    "MAITLAND NORTH",
    "MAITLAND VALE",
    "MELVILLE",
    "MINDARIBBA",
    "MOUNT DEE",
    "OAKHAMPTON",
    "OAKHAMPTON HEIGHTS",
    "POKOLBIN",
    "ROSEBROOK",
    "ROTHBURY",
    "RUTHERFORD",
    "SOUTH MAITLAND",
    "TELARAH",
    "WALLALONG",
    "WINDELLA",
    "BERRY PARK",
    "BUTTERWICK",
    "CLARENCE TOWN",
    "CLIFTLEIGH",
    "DUCKENFIELD",
    "DUNS CREEK",
    "GILLIESTON HEIGHTS",
    "GLEN MARTIN",
    "GLEN WILLIAM",
    "HARPERS HILL",
    "HEDDON GRETA",
    "HINTON",
    "LOCHINVAR",
    "LUSKINTYRE",
    "MORPETH",
    "OSWALD",
    "PHOENIX PARK",
    "RAWORTH",
    "WINDERMERE",
    "WOODVILLE",
    "BERESFIELD",
    "BLACK HILL",
    "CHISHOLM",
    "HEXHAM",
    "LENAGHAN",
    "STOCKRINGTON",
    "TARRO",
    "THORNTON",
    "TOMAGO",
    "WOODBERRY",
    "ASHTONFIELD",
    "BRUNKERVILLE",
    "BUCHANAN",
    "BUTTAI",
    "EAST MAITLAND",
    "FOUR MILE CREEK",
    "FREEMANS WATERHOLE",
    "GREEN HILLS",
    "METFORD",
    "METFORD DC",
    "MOUNT VINCENT",
    "MULBRING",
    "PITNACREE",
    "RICHMOND VALE",
    "TENAMBIT",
    "BALICKERA",
    "BRANDY HILL",
    "BUNDABAH",
    "CARRINGTON",
    "EAGLETON",
    "EAST SEAHAM",
    "HAWKS NEST",
    "HEATHERBRAE",
    "KARUAH",
    "LIMEBURNERS CREEK",
    "MILLERS FOREST",
    "NELSONS PLAINS",
    "NORTH ARM COVE",
    "OSTERLEY",
    "PINDIMAR",
    "RAYMOND TERRACE",
    "RAYMOND TERRACE EAST",
    "SEAHAM",
    "SWAN BAY",
    "TAHLEE",
    "TEA GARDENS",
    "TWELVE MILE CREEK",
    "ABERDARE",
    "ABERNETHY",
    "BELLBIRD",
    "BELLBIRD HEIGHTS",
    "CEDAR CREEK",
    "CESSNOCK",
    "CESSNOCK WEST",
    "CONGEWAI",
    "CORRABARE",
    "ELLALONG",
    "ELRINGTON",
    "GRETA MAIN",
    "KEARSLEY",
    "KITCHENER",
    "LAGUNA",
    "LOVEDALE",
    "MILLFIELD",
    "MORUBEN",
    "MOUNT VIEW",
    "NULKABA",
    "OLNEY",
    "PAXTON",
    "PAYNES CROSSING",
    "PELTON",
    "QUORROBOLONG",
    "SWEETMANS CREEK",
    "WOLLOMBI",
    "ABERMAIN",
    "BISHOPS BRIDGE",
    "LOXFORD",
    "NEATH",
    "SAWYERS GULLY",
    "WESTON",
    "KURRI KURRI",
    "PELAW MAIN",
    "STANFORD MERTHYR",
    "BUREEN",
    "DALSWINTON",
    "DENMAN",
    "GIANTS CREEK",
    "HOLLYDEEN",
    "KERRABEE",
    "MANGOOLA",
    "MARTINDALE",
    "WIDDEN",
    "YARRAWA",
    "CASSILIS",
    "MERRIWA",
    "UARBRY",
    "APPLETREE FLAT",
    "BIG RIDGE",
    "BIG YENGO",
    "BOWMANS CREEK",
    "BRIDGMAN",
    "BROKE",
    "BULGA",
    "CAMBERWELL",
    "CARROWBROOK",
    "CLYDESDALE",
    "COMBO",
    "DARLINGTON",
    "DOYLES CREEK",
    "DUNOLLY",
    "DURAL",
    "DYRRING",
    "FALBROOK",
    "FERN GULLY",
    "FORDWICH",
    "GARLAND VALLEY",
    "GLENDON",
    "GLENDON BROOK",
    "GLENNIES CREEK",
    "GLENRIDDING",
    "GOORANGOOLA",
    "GOULDSVILLE",
    "GOWRIE",
    "GREENLANDS",
    "HAMBLEDON HILL",
    "HEBDEN",
    "HOWES VALLEY",
    "HOWICK",
    "HUNTERVIEW",
    "JERRYS PLAINS",
    "LEMINGTON",
    "LONG POINT",
    "MAISON DIEU",
    "MCDOUGALLS HILL",
    "MIDDLE FALBROOK",
    "MILBRODALE",
    "MIRANNIE",
    "MITCHELLS FLAT",
    "MOUNT OLIVE",
    "MOUNT ROYAL",
    "MOUNT THORLEY",
    "OBANVALE",
    "PUTTY",
    "RAVENSWORTH",
    "REDBOURNBERRY",
    "REEDY CREEK",
    "RIXS CREEK",
    "ROUGHIT",
    "SCOTTS FLAT",
    "SEDGEFIELD",
    "SINGLETON",
    "SINGLETON HEIGHTS",
    "ST CLAIR",
    "WARKWORTH",
    "WATTLE PONDS",
    "WESTBROOK",
    "WHITTINGHAM",
    "WOLLEMI",
    "WYLIES FLAT",
    "SINGLETON MILITARY AREA",
    "SINGLETON MILPO",
    "BAERAMI",
    "BAERAMI CREEK",
    "BENGALLA",
    "CASTLE ROCK",
    "EDDERTON",
    "GUNGAL",
    "KAYUGA",
    "LIDDELL",
    "MANOBALAI",
    "MCCULLYS GAP",
    "MUSCLE CREEK",
    "MUSWELLBROOK",
    "SANDY HOLLOW",
    "WYBONG",
    "GRETA",
    "BELFORD",
    "BRANXTON",
    "DALWOOD",
    "EAST BRANXTON",
    "ELDERSLIE",
    "LAMBS VALLEY",
    "LECONFIELD",
    "LOWER BELFORD",
    "NORTH ROTHBURY",
    "STANHOPE",
    "ABERDEEN",
    "DARTBROOK",
    "DAVIS CREEK",
    "ROSSGOLE",
    "ROUCHEL",
    "ROUCHEL BROOK",
    "UPPER DARTBROOK",
    "UPPER ROUCHEL",
    "BELLTREES",
    "BRAWBOY",
    "BUNNAN",
    "DRY CREEK",
    "ELLERSTON",
    "GLENBAWN",
    "GLENROCK",
    "GUNDY",
    "KARS SPRINGS",
    "MIDDLE BROOK",
    "MOOBI",
    "MOONAN BROOK",
    "MOONAN FLAT",
    "MURULLA",
    "OMADALE",
    "OWENS GAP",
    "PAGES CREEK",
    "PARKVILLE",
    "SCONE",
    "SEGENHOE",
    "STEWARTS BROOK",
    "TOMALLA",
    "WAVERLY",
    "WINGEN",
    "WOOLOOMA",
    "ARDGLEN",
    "BLANDFORD",
    "CRAWNEY",
    "GREEN CREEK",
    "MURRURUNDI",
    "PAGES RIVER",
    "SANDY CREEK",
    "SCOTTS CREEK",
    "TIMOR",
    "BIG JACKS CREEK",
    "BRAEFIELD",
    "CATTLE CREEK",
    "CHILCOTTS CREEK",
    "LITTLE JACKS CREEK",
    "MACDONALDS CREEK",
    "PARRAWEENA",
    "WARRAH",
    "WARRAH CREEK",
    "WILLOW TREE",
    "APPLEBY",
    "BARRY",
    "BECTIVE",
    "BITHRAMERE",
    "BOWLING ALLEY POINT",
    "CALALA",
    "CARROLL",
    "DARUKA",
    "DUNCANS CREEK",
    "DUNGOWAN",
    "EAST TAMWORTH",
    "GAROO",
    "GIDLEY",
    "GOONOO GOONOO",
    "GOWRIE",
    "HALLSVILLE",
    "HANGING ROCK",
    "HILLVUE",
    "KEEPIT",
    "KINGSWOOD",
    "LOOMBERAH",
    "MOORE CREEK",
    "NEMINGHA",
    "NORTH TAMWORTH",
    "NUNDLE",
    "OGUNBIL",
    "OXLEY VALE",
    "PIALLAMORE",
    "SOMERTON",
    "SOUTH TAMWORTH",
    "TAMINDA",
    "TAMWORTH",
    "TIMBUMBURI",
    "WALLAMORE",
    "WARRAL",
    "WEABONGA",
    "WEST TAMWORTH",
    "WESTDALE",
    "WOOLOMIN",
    "WERRIS CREEK",
    "CURRABUBULA",
    "PIALLAWAY",
    "BLACKVILLE",
    "BORAMBIL",
    "BUNDELLA",
    "CAROONA"
};

const int placenameCount = sizeof(placenames) / sizeof(placenames[0]);

@end
